version: 2
jobs:
   build:
     docker:
       - image: ubuntu:16.04
     environment:
       GODIST: "go1.9.2.linux-amd64.tar.gz"
       GOPATH: /go
       GOROOT: /usr/local/go
     steps:
       - checkout

       - run: |
          export PATH=/usr/local/go/bin:/go/bin:$PATH
          proj_dir=$(pwd)

          mkdir ~/testresults

          apt-get update
          apt-get install -y libzmq5-dev curl build-essential git pkg-config wget
          cd /tmp
          curl -o $GODIST https://storage.googleapis.com/golang/$GODIST
          tar -C /usr/local -xzf $GODIST
          mkdir -p /go/src/github.com/signalfx /go/bin

          wget -O /usr/bin/dep https://github.com/golang/dep/releases/download/v0.3.2/dep-linux-amd64
          chmod +x /usr/bin/dep

          ln -s $proj_dir /go/src/github.com/signalfx/neo-agent

          ls -al /go/src/github.com/signalfx
          cd /go/src/github.com/signalfx/neo-agent
          make vendor
          scripts/circle.sh test

       - store_test_results:
           path: ~/testresults
