version: 2
jobs:
   build:
     docker:
       - image: ubuntu:16.04
     environment:
       GODIST: "go1.8.3.linux-amd64.tar.gz"
       GOPATH: /go
     steps:
       - run: |
           cd /tmp
           curl -o $GODIST https://storage.googleapis.com/golang/$GODIST
           tar -C /usr/local -xzf $GODIST
           mkdir -p /go/src/github.com/signalfx
           ln -s $CIRCLE_WORKING_DIRECTORY /go/src/github.com/signalfx/neo-agent
           curl https://glide.sh/get | sh
           apt-get install -y libzmq5-dev

       - checkout

       - run: scripts/circle.sh test
