# interval: 10
# pipeline: docker

observers:
    local-docker:
        type: docker
        config:
            hostUrl: unix:///var/run/docker.sock
    kubernetes:
        type: kubernetes
        config:
            hostUrl: https://localhost:10250
            # Whether to ignore SSL certification validation errors.
            # ignoreTLSVerify: false

monitors:
    collectd:
        type: collectd
        config:
            # If hostname is unset collectd determines the hostname at runtime.
            # hostname:
            confFile: /etc/collectd/collectd.conf
            templatesDir: /etc/signalfx/collectd/templates
            templatesMap: /etc/signalfx/collectd/templates.json
            pluginsDir: /usr/share/collectd
            staticPlugins:
                - name: writehttp-default
                  type: writehttp
                - name: signalfx-default
                  type: signalfx
                - name: docker-default
                  type: docker
                  config:
                      hostUrl: unix:///var/run/docker.sock
filters:
    debug:
        type: debug
        config: {}
    service-mapping:
        type: service-rules
        config:
            servicesFiles:
            - /etc/signalfx/collectd/custom-services.json
            - /etc/signalfx/collectd/services.json

pipelines:
    kubernetes:
    - kubernetes
    - service-mapping
    - collectd

    docker:
    - local-docker
    - service-mapping
    - collectd
