interval: 10

observers:
    local-docker:
        type: docker
        configuration:
            hostUrl: unix:///var/run/docker.sock

monitors:
    collectd:
        type: collectd
        configuration:
            confFile: /etc/collectd/collectd.conf
            templatesDir: /etc/signalfx/collectd/templates
            pluginsDir: /usr/share/collectd
            staticPlugins:
                - name: signalfx-default
                  type: signalfx
                  configuration:
                      apiToken: <API TOKEN>

filters:
    service-mapping:
        type: service-rules
        configuration:
            servicesFile: /etc/signalfx/collectd/services.json

pipeline:
    default:
    - local-docker
    - service-mapping
    - collectd
