interval: 10

observers:
    local-docker:
        type: docker
        config:
            hostUrl: unix:///var/run/docker.sock

monitors:
    collectd:
        type: collectd
        config:
            confFile: /etc/collectd/collectd.conf
            templatesDir: /etc/signalfx/collectd/templates
            templatesMap: /etc/signalfx/collectd/templates.json
            pluginsDir: /usr/share/collectd
            staticPlugins:
                - name: signalfx-default
                  type: signalfx
                  config:
                      apiToken: <API TOKEN>
                - name: docker-default
                  type: docker
                  configuration:
                      hostUrl: unix:///var/run/docker.sock
filters:
    service-mapping:
        type: service-rules
        config:
            servicesFile: /etc/signalfx/collectd/services.json

pipeline:
    default:
    - local-docker
    - service-mapping
    - collectd
