# How often to execute the pipeline.
# interval: 10

# Default pipeline to run.
# pipeline: docker

# Number of seconds before polling configuration files for changes.
# pollingInterval: 5

# Whether to poll plugin configuration files for changes.
# fileWatching: true

# If hostname is unset collectd determines the hostname at runtime.
# hostname:

# Extra dimensions to be included when reporting metrics.
# dimensions:
#   name: value

# Metric ingest URL.
# ingestURL: https://ingest.signalfx.com

plugins:
    local-docker:
        plugin: observers/docker
        url: unix:///var/run/docker.sock

    kubernetes:
        plugin: observers/kubernetes
        hostUrl: https://localhost:10250
        # Whether to ignore SSL certification validation errors.
        # ignoreTLSVerify: false

    mesosphere:
        plugin: observers/mesosphere

    collectd:
        plugin: monitors/collectd
        confFile: /etc/collectd/collectd.conf
        templatesDirs:
        - /etc/signalfx/collectd/templates
        pluginsDir: /usr/share/collectd
        staticPlugins:
            writehttp-default:
                plugin: writehttp
            signalfx-default:
                plugin: signalfx
            docker-default:
                plugin: docker
                hostUrl: unix:///var/run/docker.sock

    debug:
        plugin: filters/debug

    service-mapping:
        plugin: filters/service-rules
        servicesFiles:
        - /etc/signalfx/collectd/custom-services.json
        - /etc/signalfx/collectd/services.json

pipelines:
    mesosphere:
    - mesosphere
    - service-mapping
    - collectd

    kubernetes:
    - kubernetes
    - service-mapping
    - collectd

    docker:
    - local-docker
    - service-mapping
    - collectd
