# interval: 10
# pipeline: docker
# If hostname is unset collectd determines the hostname at runtime.
# hostname:

plugins:
    local-docker:
        plugin: observers/docker
        hostUrl: unix:///var/run/docker.sock

    kubernetes:
        plugin: observers/kubernetes
        hostUrl: https://localhost:10250
        # Whether to ignore SSL certification validation errors.
        # ignoreTLSVerify: false

    collectd:
        plugin: monitors/collectd
        confFile: /etc/collectd/collectd.conf
        templatesDir: /etc/signalfx/collectd/templates
        templatesMap: /etc/signalfx/collectd/templates.json
        pluginsDir: /usr/share/collectd
        staticPlugins:
            writehttp-default:
                plugin: writehttp
            signalfx-default:
                plugin: signalfx
            docker-default:
                plugin: docker
                hostUrl: unix:///var/run/docker.sock

    debug:
        plugin: filters/debug

    service-mapping:
        plugin: filters/service-rules
        servicesFiles:
        - /etc/signalfx/collectd/custom-services.json
        - /etc/signalfx/collectd/services.json

pipelines:
    kubernetes:
    - kubernetes
    - service-mapping
    - collectd

    docker:
    - local-docker
    - service-mapping
    - collectd
